/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.MSG_Server.CS_ServerRegister_Req', null, global);
goog.exportSymbol('proto.MSG_Server.ErrorCode', null, global);
goog.exportSymbol('proto.MSG_Server.SC_ServerRegister_Rsp', null, global);
goog.exportSymbol('proto.MSG_Server.SUBMSG', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Server.CS_ServerRegister_Req = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MSG_Server.CS_ServerRegister_Req.repeatedFields_, null);
};
goog.inherits(proto.MSG_Server.CS_ServerRegister_Req, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Server.CS_ServerRegister_Req.displayName = 'proto.MSG_Server.CS_ServerRegister_Req';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MSG_Server.CS_ServerRegister_Req.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Server.CS_ServerRegister_Req.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Server.CS_ServerRegister_Req.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Server.CS_ServerRegister_Req} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Server.CS_ServerRegister_Req.toObject = function(includeInstance, msg) {
  var f, obj = {
    servertype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    msgsList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Server.CS_ServerRegister_Req}
 */
proto.MSG_Server.CS_ServerRegister_Req.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Server.CS_ServerRegister_Req;
  return proto.MSG_Server.CS_ServerRegister_Req.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Server.CS_ServerRegister_Req} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Server.CS_ServerRegister_Req}
 */
proto.MSG_Server.CS_ServerRegister_Req.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServertype(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setMsgsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Server.CS_ServerRegister_Req.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Server.CS_ServerRegister_Req.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Server.CS_ServerRegister_Req} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Server.CS_ServerRegister_Req.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServertype();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMsgsList();
  if (f.length > 0) {
    writer.writePackedUint32(
      2,
      f
    );
  }
};


/**
 * optional int32 ServerType = 1;
 * @return {number}
 */
proto.MSG_Server.CS_ServerRegister_Req.prototype.getServertype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.MSG_Server.CS_ServerRegister_Req.prototype.setServertype = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated uint32 Msgs = 2;
 * @return {!Array<number>}
 */
proto.MSG_Server.CS_ServerRegister_Req.prototype.getMsgsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<number>} value */
proto.MSG_Server.CS_ServerRegister_Req.prototype.setMsgsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.MSG_Server.CS_ServerRegister_Req.prototype.addMsgs = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.MSG_Server.CS_ServerRegister_Req.prototype.clearMsgsList = function() {
  this.setMsgsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Server.SC_ServerRegister_Rsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Server.SC_ServerRegister_Rsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Server.SC_ServerRegister_Rsp.displayName = 'proto.MSG_Server.SC_ServerRegister_Rsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Server.SC_ServerRegister_Rsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Server.SC_ServerRegister_Rsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Server.SC_ServerRegister_Rsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    ret: jspb.Message.getFieldWithDefault(msg, 1, 0),
    identify: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Server.SC_ServerRegister_Rsp}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Server.SC_ServerRegister_Rsp;
  return proto.MSG_Server.SC_ServerRegister_Rsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Server.SC_ServerRegister_Rsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Server.SC_ServerRegister_Rsp}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.MSG_Server.ErrorCode} */ (reader.readEnum());
      msg.setRet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentify(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Server.SC_ServerRegister_Rsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Server.SC_ServerRegister_Rsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Server.SC_ServerRegister_Rsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRet();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIdentify();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ErrorCode Ret = 1;
 * @return {!proto.MSG_Server.ErrorCode}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.getRet = function() {
  return /** @type {!proto.MSG_Server.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.MSG_Server.ErrorCode} value */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.setRet = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string Identify = 2;
 * @return {string}
 */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.getIdentify = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.MSG_Server.SC_ServerRegister_Rsp.prototype.setIdentify = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.MSG_Server.SUBMSG = {
  BEGIN: 0,
  CS_SERVERREGISTER: 1,
  SC_SERVERREGISTER: 2
};

/**
 * @enum {number}
 */
proto.MSG_Server.ErrorCode = {
  INVALID: 0,
  SUCCESS: 1,
  FAIL: 2
};

goog.object.extend(exports, proto.MSG_Server);
