// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MSG_Server.proto

package MSG_Server // import "msgProto/MSG_Server"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// server
type SUBMSG int32

const (
	SUBMSG_Begin             SUBMSG = 0
	SUBMSG_CS_ServerRegister SUBMSG = 1
	SUBMSG_SC_ServerRegister SUBMSG = 2
)

var SUBMSG_name = map[int32]string{
	0: "Begin",
	1: "CS_ServerRegister",
	2: "SC_ServerRegister",
}
var SUBMSG_value = map[string]int32{
	"Begin":             0,
	"CS_ServerRegister": 1,
	"SC_ServerRegister": 2,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Server_31b1d8f3a4ce087e, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_Invalid ErrorCode = 0
	ErrorCode_Success ErrorCode = 1
	ErrorCode_Fail    ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "Invalid",
	1: "Success",
	2: "Fail",
}
var ErrorCode_value = map[string]int32{
	"Invalid": 0,
	"Success": 1,
	"Fail":    2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Server_31b1d8f3a4ce087e, []int{1}
}

// CS_ServerRegister
type CS_ServerRegister_Req struct {
	ServerType           int32    `protobuf:"varint,1,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	Msgs                 []uint32 `protobuf:"varint,2,rep,packed,name=Msgs,proto3" json:"Msgs,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_ServerRegister_Req) Reset()         { *m = CS_ServerRegister_Req{} }
func (m *CS_ServerRegister_Req) String() string { return proto.CompactTextString(m) }
func (*CS_ServerRegister_Req) ProtoMessage()    {}
func (*CS_ServerRegister_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Server_31b1d8f3a4ce087e, []int{0}
}
func (m *CS_ServerRegister_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_ServerRegister_Req.Unmarshal(m, b)
}
func (m *CS_ServerRegister_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_ServerRegister_Req.Marshal(b, m, deterministic)
}
func (dst *CS_ServerRegister_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_ServerRegister_Req.Merge(dst, src)
}
func (m *CS_ServerRegister_Req) XXX_Size() int {
	return xxx_messageInfo_CS_ServerRegister_Req.Size(m)
}
func (m *CS_ServerRegister_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_ServerRegister_Req.DiscardUnknown(m)
}

var xxx_messageInfo_CS_ServerRegister_Req proto.InternalMessageInfo

func (m *CS_ServerRegister_Req) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *CS_ServerRegister_Req) GetMsgs() []uint32 {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func (m *CS_ServerRegister_Req) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// SC_ServerRegister
type SC_ServerRegister_Rsp struct {
	Ret                  ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=MSG_Server.ErrorCode" json:"Ret,omitempty"`
	Identify             string    `protobuf:"bytes,2,opt,name=Identify,proto3" json:"Identify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SC_ServerRegister_Rsp) Reset()         { *m = SC_ServerRegister_Rsp{} }
func (m *SC_ServerRegister_Rsp) String() string { return proto.CompactTextString(m) }
func (*SC_ServerRegister_Rsp) ProtoMessage()    {}
func (*SC_ServerRegister_Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Server_31b1d8f3a4ce087e, []int{1}
}
func (m *SC_ServerRegister_Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_ServerRegister_Rsp.Unmarshal(m, b)
}
func (m *SC_ServerRegister_Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_ServerRegister_Rsp.Marshal(b, m, deterministic)
}
func (dst *SC_ServerRegister_Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_ServerRegister_Rsp.Merge(dst, src)
}
func (m *SC_ServerRegister_Rsp) XXX_Size() int {
	return xxx_messageInfo_SC_ServerRegister_Rsp.Size(m)
}
func (m *SC_ServerRegister_Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_ServerRegister_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_SC_ServerRegister_Rsp proto.InternalMessageInfo

func (m *SC_ServerRegister_Rsp) GetRet() ErrorCode {
	if m != nil {
		return m.Ret
	}
	return ErrorCode_Invalid
}

func (m *SC_ServerRegister_Rsp) GetIdentify() string {
	if m != nil {
		return m.Identify
	}
	return ""
}

func init() {
	proto.RegisterType((*CS_ServerRegister_Req)(nil), "MSG_Server.CS_ServerRegister_Req")
	proto.RegisterType((*SC_ServerRegister_Rsp)(nil), "MSG_Server.SC_ServerRegister_Rsp")
	proto.RegisterEnum("MSG_Server.SUBMSG", SUBMSG_name, SUBMSG_value)
	proto.RegisterEnum("MSG_Server.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("MSG_Server.proto", fileDescriptor_MSG_Server_31b1d8f3a4ce087e) }

var fileDescriptor_MSG_Server_31b1d8f3a4ce087e = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x86, 0xd7, 0xee, 0xb3, 0x47, 0x94, 0x78, 0x24, 0x10, 0xbc, 0x90, 0xb2, 0x1b, 0xcb, 0x2e,
	0x36, 0xd0, 0x5f, 0x60, 0x8b, 0x8e, 0x5d, 0x14, 0x24, 0x51, 0x2f, 0x44, 0x18, 0x73, 0x3d, 0x96,
	0xc0, 0x6c, 0x6a, 0x52, 0x07, 0xfb, 0xf7, 0xd2, 0xaa, 0xdb, 0xa0, 0x77, 0x79, 0x1e, 0x92, 0x9c,
	0xf7, 0xbc, 0xc0, 0x52, 0x35, 0x5f, 0x2a, 0xb2, 0x5b, 0xb2, 0xd3, 0xd2, 0x9a, 0xca, 0x20, 0x1c,
	0xcc, 0x98, 0x80, 0x27, 0xea, 0x0f, 0x24, 0xe5, 0xda, 0x55, 0x64, 0x97, 0x92, 0xbe, 0xf0, 0x0a,
	0xe0, 0xd7, 0x3e, 0xed, 0x4a, 0x12, 0x5e, 0xe8, 0x45, 0x7d, 0x79, 0x64, 0x10, 0xa1, 0x97, 0xba,
	0xdc, 0x09, 0x3f, 0xec, 0x46, 0xa7, 0xb2, 0x39, 0xa3, 0x80, 0xe1, 0x0b, 0x59, 0xa7, 0x4d, 0x21,
	0xba, 0xcd, 0x83, 0x7f, 0x1c, 0xbf, 0x01, 0x57, 0x49, 0x6b, 0x8c, 0x2b, 0xf1, 0x1a, 0xba, 0x92,
	0xaa, 0xe6, 0xff, 0xb3, 0x1b, 0x3e, 0x3d, 0xca, 0x7a, 0x6f, 0xad, 0xb1, 0x89, 0xc9, 0x48, 0xd6,
	0x37, 0xf0, 0x12, 0x46, 0x8b, 0x8c, 0x8a, 0x4a, 0x7f, 0xec, 0x84, 0x1f, 0x7a, 0x51, 0x20, 0xf7,
	0x3c, 0xb9, 0x83, 0x81, 0x7a, 0x8e, 0x53, 0x35, 0xc7, 0x00, 0xfa, 0x31, 0xe5, 0xba, 0x60, 0x1d,
	0xe4, 0x70, 0xde, 0xda, 0x8c, 0x79, 0xb5, 0x6e, 0x25, 0x61, 0xfe, 0x64, 0x06, 0xc1, 0x7e, 0x20,
	0x9e, 0xc0, 0x70, 0x51, 0x6c, 0x57, 0x1b, 0x9d, 0xb1, 0x4e, 0x0d, 0xea, 0x7b, 0xbd, 0x26, 0xe7,
	0x98, 0x87, 0x23, 0xe8, 0x3d, 0xac, 0xf4, 0x86, 0xf9, 0x31, 0x7f, 0xbd, 0xf8, 0x74, 0xf9, 0x63,
	0x5d, 0xe8, 0xec, 0x90, 0xfa, 0x7d, 0xd0, 0x54, 0x7c, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9f,
	0xf6, 0x5c, 0xef, 0x76, 0x01, 0x00, 0x00,
}
