// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MSG_Login.proto

package MSG_Login // import "msgProto/MSG_Login"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// server
type SUBMSG int32

const (
	SUBMSG_Begin           SUBMSG = 0
	SUBMSG_CS_UserBind     SUBMSG = 1
	SUBMSG_SC_UserBind     SUBMSG = 2
	SUBMSG_CS_UserRegister SUBMSG = 3
	SUBMSG_SC_UserRegister SUBMSG = 4
	SUBMSG_CS_Login        SUBMSG = 5
	SUBMSG_SC_Login        SUBMSG = 6
	SUBMSG_CS_Logout       SUBMSG = 7
	SUBMSG_SC_Logout       SUBMSG = 8
	SUBMSG_CS_Certificate  SUBMSG = 9
	SUBMSG_SC_Certificate  SUBMSG = 10
)

var SUBMSG_name = map[int32]string{
	0:  "Begin",
	1:  "CS_UserBind",
	2:  "SC_UserBind",
	3:  "CS_UserRegister",
	4:  "SC_UserRegister",
	5:  "CS_Login",
	6:  "SC_Login",
	7:  "CS_Logout",
	8:  "SC_Logout",
	9:  "CS_Certificate",
	10: "SC_Certificate",
}
var SUBMSG_value = map[string]int32{
	"Begin":           0,
	"CS_UserBind":     1,
	"SC_UserBind":     2,
	"CS_UserRegister": 3,
	"SC_UserRegister": 4,
	"CS_Login":        5,
	"SC_Login":        6,
	"CS_Logout":       7,
	"SC_Logout":       8,
	"CS_Certificate":  9,
	"SC_Certificate":  10,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_Invalid                 ErrorCode = 0
	ErrorCode_Success                 ErrorCode = 1
	ErrorCode_Fail                    ErrorCode = 2
	ErrorCode_UserNotExistOrPasswdErr ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	0: "Invalid",
	1: "Success",
	2: "Fail",
	3: "UserNotExistOrPasswdErr",
}
var ErrorCode_value = map[string]int32{
	"Invalid": 0,
	"Success": 1,
	"Fail":    2,
	"UserNotExistOrPasswdErr": 3,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{1}
}

// CS_UserBind
type CS_UserBind_Req struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_UserBind_Req) Reset()         { *m = CS_UserBind_Req{} }
func (m *CS_UserBind_Req) String() string { return proto.CompactTextString(m) }
func (*CS_UserBind_Req) ProtoMessage()    {}
func (*CS_UserBind_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{0}
}
func (m *CS_UserBind_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_UserBind_Req.Unmarshal(m, b)
}
func (m *CS_UserBind_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_UserBind_Req.Marshal(b, m, deterministic)
}
func (dst *CS_UserBind_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_UserBind_Req.Merge(dst, src)
}
func (m *CS_UserBind_Req) XXX_Size() int {
	return xxx_messageInfo_CS_UserBind_Req.Size(m)
}
func (m *CS_UserBind_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_UserBind_Req.DiscardUnknown(m)
}

var xxx_messageInfo_CS_UserBind_Req proto.InternalMessageInfo

func (m *CS_UserBind_Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_UserBind_Req) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

// CS_UserRegister
type CS_UserRegister_Req struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	DeviceSerial         string   `protobuf:"bytes,3,opt,name=DeviceSerial,proto3" json:"DeviceSerial,omitempty"`
	DeviceName           string   `protobuf:"bytes,4,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_UserRegister_Req) Reset()         { *m = CS_UserRegister_Req{} }
func (m *CS_UserRegister_Req) String() string { return proto.CompactTextString(m) }
func (*CS_UserRegister_Req) ProtoMessage()    {}
func (*CS_UserRegister_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{1}
}
func (m *CS_UserRegister_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_UserRegister_Req.Unmarshal(m, b)
}
func (m *CS_UserRegister_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_UserRegister_Req.Marshal(b, m, deterministic)
}
func (dst *CS_UserRegister_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_UserRegister_Req.Merge(dst, src)
}
func (m *CS_UserRegister_Req) XXX_Size() int {
	return xxx_messageInfo_CS_UserRegister_Req.Size(m)
}
func (m *CS_UserRegister_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_UserRegister_Req.DiscardUnknown(m)
}

var xxx_messageInfo_CS_UserRegister_Req proto.InternalMessageInfo

func (m *CS_UserRegister_Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_UserRegister_Req) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *CS_UserRegister_Req) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *CS_UserRegister_Req) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

// SC_UserRegister
type SC_UserRegister_Rsp struct {
	Ret                  ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=MSG_Login.ErrorCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SC_UserRegister_Rsp) Reset()         { *m = SC_UserRegister_Rsp{} }
func (m *SC_UserRegister_Rsp) String() string { return proto.CompactTextString(m) }
func (*SC_UserRegister_Rsp) ProtoMessage()    {}
func (*SC_UserRegister_Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{2}
}
func (m *SC_UserRegister_Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_UserRegister_Rsp.Unmarshal(m, b)
}
func (m *SC_UserRegister_Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_UserRegister_Rsp.Marshal(b, m, deterministic)
}
func (dst *SC_UserRegister_Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_UserRegister_Rsp.Merge(dst, src)
}
func (m *SC_UserRegister_Rsp) XXX_Size() int {
	return xxx_messageInfo_SC_UserRegister_Rsp.Size(m)
}
func (m *SC_UserRegister_Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_UserRegister_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_SC_UserRegister_Rsp proto.InternalMessageInfo

func (m *SC_UserRegister_Rsp) GetRet() ErrorCode {
	if m != nil {
		return m.Ret
	}
	return ErrorCode_Invalid
}

// CS_Login
type CS_Login_Req struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	DeviceSerial         string   `protobuf:"bytes,3,opt,name=DeviceSerial,proto3" json:"DeviceSerial,omitempty"`
	DeviceName           string   `protobuf:"bytes,4,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Login_Req) Reset()         { *m = CS_Login_Req{} }
func (m *CS_Login_Req) String() string { return proto.CompactTextString(m) }
func (*CS_Login_Req) ProtoMessage()    {}
func (*CS_Login_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{3}
}
func (m *CS_Login_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Login_Req.Unmarshal(m, b)
}
func (m *CS_Login_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Login_Req.Marshal(b, m, deterministic)
}
func (dst *CS_Login_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Login_Req.Merge(dst, src)
}
func (m *CS_Login_Req) XXX_Size() int {
	return xxx_messageInfo_CS_Login_Req.Size(m)
}
func (m *CS_Login_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Login_Req.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Login_Req proto.InternalMessageInfo

func (m *CS_Login_Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_Login_Req) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *CS_Login_Req) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *CS_Login_Req) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

// SC_Login
type SC_Login_Rsp struct {
	Ret                  ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=MSG_Login.ErrorCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SC_Login_Rsp) Reset()         { *m = SC_Login_Rsp{} }
func (m *SC_Login_Rsp) String() string { return proto.CompactTextString(m) }
func (*SC_Login_Rsp) ProtoMessage()    {}
func (*SC_Login_Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_MSG_Login_a0f656245d608f59, []int{4}
}
func (m *SC_Login_Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Login_Rsp.Unmarshal(m, b)
}
func (m *SC_Login_Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Login_Rsp.Marshal(b, m, deterministic)
}
func (dst *SC_Login_Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Login_Rsp.Merge(dst, src)
}
func (m *SC_Login_Rsp) XXX_Size() int {
	return xxx_messageInfo_SC_Login_Rsp.Size(m)
}
func (m *SC_Login_Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Login_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Login_Rsp proto.InternalMessageInfo

func (m *SC_Login_Rsp) GetRet() ErrorCode {
	if m != nil {
		return m.Ret
	}
	return ErrorCode_Invalid
}

func init() {
	proto.RegisterType((*CS_UserBind_Req)(nil), "MSG_Login.CS_UserBind_Req")
	proto.RegisterType((*CS_UserRegister_Req)(nil), "MSG_Login.CS_UserRegister_Req")
	proto.RegisterType((*SC_UserRegister_Rsp)(nil), "MSG_Login.SC_UserRegister_Rsp")
	proto.RegisterType((*CS_Login_Req)(nil), "MSG_Login.CS_Login_Req")
	proto.RegisterType((*SC_Login_Rsp)(nil), "MSG_Login.SC_Login_Rsp")
	proto.RegisterEnum("MSG_Login.SUBMSG", SUBMSG_name, SUBMSG_value)
	proto.RegisterEnum("MSG_Login.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("MSG_Login.proto", fileDescriptor_MSG_Login_a0f656245d608f59) }

var fileDescriptor_MSG_Login_a0f656245d608f59 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0x41, 0xab, 0xd3, 0x40,
	0x14, 0x85, 0x5f, 0x9a, 0xbe, 0xb4, 0xb9, 0x2f, 0xbe, 0x0e, 0xb7, 0x0f, 0x0d, 0x08, 0x22, 0x59,
	0x88, 0xbc, 0x45, 0x05, 0x05, 0x77, 0x2e, 0xcc, 0x58, 0x8b, 0xd0, 0xd6, 0x92, 0xa1, 0x1b, 0x37,
	0x21, 0x26, 0x63, 0x18, 0x68, 0x33, 0x75, 0x66, 0x5a, 0xfd, 0x01, 0xee, 0xfc, 0x55, 0xfe, 0x33,
	0x99, 0xa4, 0x89, 0x6d, 0x57, 0xe2, 0xc6, 0xe5, 0xf9, 0xce, 0x30, 0x9c, 0x39, 0xf7, 0x0e, 0x8c,
	0x16, 0x6c, 0x96, 0xce, 0x65, 0x29, 0xaa, 0xc9, 0x4e, 0x49, 0x23, 0xd1, 0xef, 0x40, 0x44, 0x61,
	0x44, 0x59, 0xba, 0xd6, 0x5c, 0xc5, 0xa2, 0x2a, 0xd2, 0x84, 0x7f, 0xc5, 0x10, 0x06, 0x6f, 0xf3,
	0x5c, 0xee, 0x2b, 0x13, 0x3a, 0x4f, 0x9d, 0xe7, 0x7e, 0xd2, 0x4a, 0x7c, 0x08, 0xde, 0x2a, 0xd3,
	0xfa, 0x5b, 0x11, 0xf6, 0x6a, 0xe3, 0xa8, 0xa2, 0x9f, 0x0e, 0x8c, 0x8f, 0xb7, 0x24, 0xbc, 0x14,
	0xda, 0x70, 0xf5, 0x6f, 0x37, 0x61, 0x04, 0xc1, 0x3b, 0x7e, 0x10, 0x39, 0x67, 0x5c, 0x89, 0x6c,
	0x13, 0xba, 0xb5, 0x7b, 0xc6, 0xf0, 0x09, 0x40, 0xa3, 0x97, 0xd9, 0x96, 0x87, 0xfd, 0xfa, 0xc4,
	0x09, 0x89, 0xde, 0xc0, 0x98, 0xd1, 0x8b, 0x30, 0x7a, 0x87, 0xcf, 0xc0, 0x4d, 0x78, 0x13, 0xe4,
	0xf6, 0xe5, 0xdd, 0xe4, 0x4f, 0x27, 0x53, 0xa5, 0xa4, 0xa2, 0xb2, 0xe0, 0x89, 0x3d, 0x10, 0xfd,
	0x70, 0x20, 0xa0, 0xac, 0xf1, 0xfe, 0xe3, 0x2b, 0x5e, 0x43, 0xc0, 0x68, 0x9b, 0xe2, 0xef, 0xe3,
	0xdf, 0xff, 0x72, 0xc0, 0x63, 0xeb, 0x78, 0xc1, 0x66, 0xe8, 0xc3, 0x75, 0xcc, 0x4b, 0x51, 0x91,
	0x2b, 0x1c, 0xc1, 0xcd, 0xc9, 0x98, 0x89, 0x63, 0xc1, 0xb1, 0xa4, 0x1a, 0xf4, 0x70, 0xdc, 0x2d,
	0x42, 0xdb, 0x1a, 0x71, 0x2d, 0xbc, 0xa8, 0x92, 0xf4, 0x31, 0x80, 0x61, 0xdb, 0x0f, 0xb9, 0xb6,
	0xaa, 0xcd, 0x49, 0x3c, 0x7c, 0x00, 0x7e, 0xe3, 0xc9, 0xbd, 0x21, 0x03, 0x2b, 0x1b, 0xd3, 0xca,
	0x21, 0x22, 0xdc, 0x52, 0x96, 0x52, 0xae, 0x8c, 0xf8, 0x22, 0xf2, 0xcc, 0x70, 0xe2, 0x5b, 0xc6,
	0xe8, 0x19, 0x83, 0xfb, 0x39, 0xf8, 0xdd, 0xab, 0xf0, 0x06, 0x06, 0x1f, 0xaa, 0x43, 0xb6, 0x11,
	0x05, 0xb9, 0xb2, 0x82, 0xed, 0xf3, 0x9c, 0x6b, 0x4d, 0x1c, 0x1c, 0x42, 0xff, 0x7d, 0x26, 0x36,
	0xa4, 0x87, 0x8f, 0xe1, 0x91, 0x0d, 0xb9, 0x94, 0x66, 0xfa, 0x5d, 0x68, 0xf3, 0x51, 0x35, 0x83,
	0x98, 0x2a, 0x45, 0xdc, 0xf8, 0xee, 0x13, 0x6e, 0x75, 0xb9, 0xb2, 0x9b, 0xff, 0xa2, 0xab, 0xed,
	0xb3, 0x57, 0x7f, 0x85, 0x57, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x3a, 0x41, 0x5b, 0x1d,
	0x03, 0x00, 0x00,
}
