/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.MSG_Player.BaseMoney_Repeat', null, global);
goog.exportSymbol('proto.MSG_Player.BasePlayerInfo_Repeat', null, global);
goog.exportSymbol('proto.MSG_Player.CS_EnterServer_Req', null, global);
goog.exportSymbol('proto.MSG_Player.CS_LeaveServer_Req', null, global);
goog.exportSymbol('proto.MSG_Player.CS_PlayerInfo_Req', null, global);
goog.exportSymbol('proto.MSG_Player.ErrorCode', null, global);
goog.exportSymbol('proto.MSG_Player.SC_EnterServer_Rsp', null, global);
goog.exportSymbol('proto.MSG_Player.SC_LeaveServer_Rsp', null, global);
goog.exportSymbol('proto.MSG_Player.SC_PlayerInfo_Rsp', null, global);
goog.exportSymbol('proto.MSG_Player.SUBMSG', null, global);
goog.exportSymbol('proto.MSG_Player.emBaseInfo', null, global);
goog.exportSymbol('proto.MSG_Player.emBaseMoney', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.BasePlayerInfo_Repeat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.BasePlayerInfo_Repeat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.BasePlayerInfo_Repeat.displayName = 'proto.MSG_Player.BasePlayerInfo_Repeat';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.BasePlayerInfo_Repeat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.BasePlayerInfo_Repeat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.BasePlayerInfo_Repeat.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    level: jspb.Message.getFieldWithDefault(msg, 2, 0),
    headicon: jspb.Message.getFieldWithDefault(msg, 3, ""),
    dbid: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.BasePlayerInfo_Repeat}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.BasePlayerInfo_Repeat;
  return proto.MSG_Player.BasePlayerInfo_Repeat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.BasePlayerInfo_Repeat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.BasePlayerInfo_Repeat}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLevel(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeadicon(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDbid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.BasePlayerInfo_Repeat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.BasePlayerInfo_Repeat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.BasePlayerInfo_Repeat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHeadicon();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDbid();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string Name = 1;
 * @return {string}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 Level = 2;
 * @return {number}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.setLevel = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string HeadIcon = 3;
 * @return {string}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.getHeadicon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.setHeadicon = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 DBID = 4;
 * @return {number}
 */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.getDbid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.MSG_Player.BasePlayerInfo_Repeat.prototype.setDbid = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.BaseMoney_Repeat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.BaseMoney_Repeat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.BaseMoney_Repeat.displayName = 'proto.MSG_Player.BaseMoney_Repeat';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.BaseMoney_Repeat.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.BaseMoney_Repeat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.BaseMoney_Repeat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.BaseMoney_Repeat.toObject = function(includeInstance, msg) {
  var f, obj = {
    coin: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.BaseMoney_Repeat}
 */
proto.MSG_Player.BaseMoney_Repeat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.BaseMoney_Repeat;
  return proto.MSG_Player.BaseMoney_Repeat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.BaseMoney_Repeat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.BaseMoney_Repeat}
 */
proto.MSG_Player.BaseMoney_Repeat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCoin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.BaseMoney_Repeat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.BaseMoney_Repeat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.BaseMoney_Repeat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.BaseMoney_Repeat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCoin();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 Coin = 1;
 * @return {number}
 */
proto.MSG_Player.BaseMoney_Repeat.prototype.getCoin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.MSG_Player.BaseMoney_Repeat.prototype.setCoin = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.CS_EnterServer_Req = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.CS_EnterServer_Req, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.CS_EnterServer_Req.displayName = 'proto.MSG_Player.CS_EnterServer_Req';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.CS_EnterServer_Req.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.CS_EnterServer_Req.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.CS_EnterServer_Req} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_EnterServer_Req.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.CS_EnterServer_Req}
 */
proto.MSG_Player.CS_EnterServer_Req.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.CS_EnterServer_Req;
  return proto.MSG_Player.CS_EnterServer_Req.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.CS_EnterServer_Req} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.CS_EnterServer_Req}
 */
proto.MSG_Player.CS_EnterServer_Req.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.CS_EnterServer_Req.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.CS_EnterServer_Req.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.CS_EnterServer_Req} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_EnterServer_Req.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.SC_EnterServer_Rsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.SC_EnterServer_Rsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.SC_EnterServer_Rsp.displayName = 'proto.MSG_Player.SC_EnterServer_Rsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.SC_EnterServer_Rsp.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.SC_EnterServer_Rsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.SC_EnterServer_Rsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_EnterServer_Rsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    ret: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.SC_EnterServer_Rsp}
 */
proto.MSG_Player.SC_EnterServer_Rsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.SC_EnterServer_Rsp;
  return proto.MSG_Player.SC_EnterServer_Rsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.SC_EnterServer_Rsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.SC_EnterServer_Rsp}
 */
proto.MSG_Player.SC_EnterServer_Rsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.MSG_Player.ErrorCode} */ (reader.readEnum());
      msg.setRet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.SC_EnterServer_Rsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.SC_EnterServer_Rsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.SC_EnterServer_Rsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_EnterServer_Rsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRet();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional ErrorCode Ret = 1;
 * @return {!proto.MSG_Player.ErrorCode}
 */
proto.MSG_Player.SC_EnterServer_Rsp.prototype.getRet = function() {
  return /** @type {!proto.MSG_Player.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.MSG_Player.ErrorCode} value */
proto.MSG_Player.SC_EnterServer_Rsp.prototype.setRet = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.CS_LeaveServer_Req = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.CS_LeaveServer_Req, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.CS_LeaveServer_Req.displayName = 'proto.MSG_Player.CS_LeaveServer_Req';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.CS_LeaveServer_Req.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.CS_LeaveServer_Req.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.CS_LeaveServer_Req} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_LeaveServer_Req.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.CS_LeaveServer_Req}
 */
proto.MSG_Player.CS_LeaveServer_Req.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.CS_LeaveServer_Req;
  return proto.MSG_Player.CS_LeaveServer_Req.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.CS_LeaveServer_Req} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.CS_LeaveServer_Req}
 */
proto.MSG_Player.CS_LeaveServer_Req.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.CS_LeaveServer_Req.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.CS_LeaveServer_Req.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.CS_LeaveServer_Req} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_LeaveServer_Req.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.SC_LeaveServer_Rsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.SC_LeaveServer_Rsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.SC_LeaveServer_Rsp.displayName = 'proto.MSG_Player.SC_LeaveServer_Rsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.SC_LeaveServer_Rsp.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.SC_LeaveServer_Rsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.SC_LeaveServer_Rsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_LeaveServer_Rsp.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.SC_LeaveServer_Rsp}
 */
proto.MSG_Player.SC_LeaveServer_Rsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.SC_LeaveServer_Rsp;
  return proto.MSG_Player.SC_LeaveServer_Rsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.SC_LeaveServer_Rsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.SC_LeaveServer_Rsp}
 */
proto.MSG_Player.SC_LeaveServer_Rsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.SC_LeaveServer_Rsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.SC_LeaveServer_Rsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.SC_LeaveServer_Rsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_LeaveServer_Rsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.CS_PlayerInfo_Req = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.CS_PlayerInfo_Req, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.CS_PlayerInfo_Req.displayName = 'proto.MSG_Player.CS_PlayerInfo_Req';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.CS_PlayerInfo_Req.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.CS_PlayerInfo_Req.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.CS_PlayerInfo_Req} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_PlayerInfo_Req.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.CS_PlayerInfo_Req}
 */
proto.MSG_Player.CS_PlayerInfo_Req.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.CS_PlayerInfo_Req;
  return proto.MSG_Player.CS_PlayerInfo_Req.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.CS_PlayerInfo_Req} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.CS_PlayerInfo_Req}
 */
proto.MSG_Player.CS_PlayerInfo_Req.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.CS_PlayerInfo_Req.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.CS_PlayerInfo_Req.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.CS_PlayerInfo_Req} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.CS_PlayerInfo_Req.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.SC_PlayerInfo_Rsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.SC_PlayerInfo_Rsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.SC_PlayerInfo_Rsp.displayName = 'proto.MSG_Player.SC_PlayerInfo_Rsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.SC_PlayerInfo_Rsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    baseinfo: (f = msg.getBaseinfo()) && proto.MSG_Player.BasePlayerInfo_Repeat.toObject(includeInstance, f),
    basemoney: (f = msg.getBasemoney()) && proto.MSG_Player.BaseMoney_Repeat.toObject(includeInstance, f),
    ret: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.SC_PlayerInfo_Rsp}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.SC_PlayerInfo_Rsp;
  return proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.SC_PlayerInfo_Rsp}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MSG_Player.BasePlayerInfo_Repeat;
      reader.readMessage(value,proto.MSG_Player.BasePlayerInfo_Repeat.deserializeBinaryFromReader);
      msg.setBaseinfo(value);
      break;
    case 2:
      var value = new proto.MSG_Player.BaseMoney_Repeat;
      reader.readMessage(value,proto.MSG_Player.BaseMoney_Repeat.deserializeBinaryFromReader);
      msg.setBasemoney(value);
      break;
    case 3:
      var value = /** @type {!proto.MSG_Player.ErrorCode} */ (reader.readEnum());
      msg.setRet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.SC_PlayerInfo_Rsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.MSG_Player.BasePlayerInfo_Repeat.serializeBinaryToWriter
    );
  }
  f = message.getBasemoney();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MSG_Player.BaseMoney_Repeat.serializeBinaryToWriter
    );
  }
  f = message.getRet();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional BasePlayerInfo_Repeat baseInfo = 1;
 * @return {?proto.MSG_Player.BasePlayerInfo_Repeat}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getBaseinfo = function() {
  return /** @type{?proto.MSG_Player.BasePlayerInfo_Repeat} */ (
    jspb.Message.getWrapperField(this, proto.MSG_Player.BasePlayerInfo_Repeat, 1));
};


/** @param {?proto.MSG_Player.BasePlayerInfo_Repeat|undefined} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setBaseinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.clearBaseinfo = function() {
  this.setBaseinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.hasBaseinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BaseMoney_Repeat baseMoney = 2;
 * @return {?proto.MSG_Player.BaseMoney_Repeat}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getBasemoney = function() {
  return /** @type{?proto.MSG_Player.BaseMoney_Repeat} */ (
    jspb.Message.getWrapperField(this, proto.MSG_Player.BaseMoney_Repeat, 2));
};


/** @param {?proto.MSG_Player.BaseMoney_Repeat|undefined} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setBasemoney = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.clearBasemoney = function() {
  this.setBasemoney(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.hasBasemoney = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ErrorCode Ret = 3;
 * @return {!proto.MSG_Player.ErrorCode}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getRet = function() {
  return /** @type {!proto.MSG_Player.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.MSG_Player.ErrorCode} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setRet = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.MSG_Player.SUBMSG = {
  BEGIN: 0,
  CS_ENTERSERVER: 1,
  SC_ENTERSERVER: 2,
  CS_LEAVESERVER: 3,
  SC_LEAVESERVER: 4,
  CS_PLAYERINFO: 5,
  SC_PLAYERINFO: 6
};

/**
 * @enum {number}
 */
proto.MSG_Player.ErrorCode = {
  INVALID: 0,
  SUCCESS: 1,
  FAIL: 2
};

/**
 * @enum {number}
 */
proto.MSG_Player.emBaseInfo = {
  BASEINVALID: 0,
  NAME: 1,
  LEVEL: 2,
  HEADICON: 3,
  DBID: 4
};

/**
 * @enum {number}
 */
proto.MSG_Player.emBaseMoney = {
  MONEYINVALID: 0,
  COIN: 1
};

goog.object.extend(exports, proto.MSG_Player);
