// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: acc.proto

package akmessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_AccRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Pwd string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *CS_AccRegister) Reset() {
	*x = CS_AccRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_AccRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_AccRegister) ProtoMessage() {}

func (x *CS_AccRegister) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_AccRegister.ProtoReflect.Descriptor instead.
func (*CS_AccRegister) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{0}
}

func (x *CS_AccRegister) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *CS_AccRegister) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type SC_AccRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_AccRegister) Reset() {
	*x = SC_AccRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_AccRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_AccRegister) ProtoMessage() {}

func (x *SC_AccRegister) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_AccRegister.ProtoReflect.Descriptor instead.
func (*SC_AccRegister) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{1}
}

func (x *SC_AccRegister) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

type CS_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Pwd string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *CS_Login) Reset() {
	*x = CS_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Login) ProtoMessage() {}

func (x *CS_Login) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Login.ProtoReflect.Descriptor instead.
func (*CS_Login) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{2}
}

func (x *CS_Login) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *CS_Login) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type SC_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_Login) Reset() {
	*x = SC_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Login) ProtoMessage() {}

func (x *SC_Login) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Login.ProtoReflect.Descriptor instead.
func (*SC_Login) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{3}
}

func (x *SC_Login) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

type CS_Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_Logout) Reset() {
	*x = CS_Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Logout) ProtoMessage() {}

func (x *CS_Logout) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Logout.ProtoReflect.Descriptor instead.
func (*CS_Logout) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{4}
}

type SC_Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SC_Logout) Reset() {
	*x = SC_Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Logout) ProtoMessage() {}

func (x *SC_Logout) ProtoReflect() protoreflect.Message {
	mi := &file_acc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Logout.ProtoReflect.Descriptor instead.
func (*SC_Logout) Descriptor() ([]byte, []int) {
	return file_acc_proto_rawDescGZIP(), []int{5}
}

var File_acc_proto protoreflect.FileDescriptor

var file_acc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0e,
	0x43, 0x53, 0x5f, 0x41, 0x63, 0x63, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x77, 0x64, 0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x43, 0x5f, 0x41, 0x63, 0x63, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x22, 0x2e, 0x0a, 0x08, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x77, 0x64, 0x22, 0x28, 0x0a, 0x08, 0x53, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c,
	0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x0b, 0x0a, 0x09,
	0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x43, 0x5f,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x61, 0x6b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_acc_proto_rawDescOnce sync.Once
	file_acc_proto_rawDescData = file_acc_proto_rawDesc
)

func file_acc_proto_rawDescGZIP() []byte {
	file_acc_proto_rawDescOnce.Do(func() {
		file_acc_proto_rawDescData = protoimpl.X.CompressGZIP(file_acc_proto_rawDescData)
	})
	return file_acc_proto_rawDescData
}

var file_acc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_acc_proto_goTypes = []interface{}{
	(*CS_AccRegister)(nil), // 0: CS_AccRegister
	(*SC_AccRegister)(nil), // 1: SC_AccRegister
	(*CS_Login)(nil),       // 2: CS_Login
	(*SC_Login)(nil),       // 3: SC_Login
	(*CS_Logout)(nil),      // 4: CS_Logout
	(*SC_Logout)(nil),      // 5: SC_Logout
	(ErrorCode)(0),         // 6: ErrorCode
}
var file_acc_proto_depIdxs = []int32{
	6, // 0: SC_AccRegister.Ret:type_name -> ErrorCode
	6, // 1: SC_Login.Ret:type_name -> ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_acc_proto_init() }
func file_acc_proto_init() {
	if File_acc_proto != nil {
		return
	}
	file_errorcode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_acc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_AccRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_AccRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acc_proto_goTypes,
		DependencyIndexes: file_acc_proto_depIdxs,
		MessageInfos:      file_acc_proto_msgTypes,
	}.Build()
	File_acc_proto = out.File
	file_acc_proto_rawDesc = nil
	file_acc_proto_goTypes = nil
	file_acc_proto_depIdxs = nil
}
