// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: friend.proto

package akmessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EFriendType int32

const (
	EFriendType_EFT_None     EFriendType = 0
	EFriendType_EFT_Friend   EFriendType = 1 //好友
	EFriendType_EFT_Stranger EFriendType = 2 //陌生人
	EFriendType_EFT_Guild    EFriendType = 3 //帮会朋友
)

// Enum value maps for EFriendType.
var (
	EFriendType_name = map[int32]string{
		0: "EFT_None",
		1: "EFT_Friend",
		2: "EFT_Stranger",
		3: "EFT_Guild",
	}
	EFriendType_value = map[string]int32{
		"EFT_None":     0,
		"EFT_Friend":   1,
		"EFT_Stranger": 2,
		"EFT_Guild":    3,
	}
)

func (x EFriendType) Enum() *EFriendType {
	p := new(EFriendType)
	*p = x
	return p
}

func (x EFriendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EFriendType) Descriptor() protoreflect.EnumDescriptor {
	return file_friend_proto_enumTypes[0].Descriptor()
}

func (EFriendType) Type() protoreflect.EnumType {
	return &file_friend_proto_enumTypes[0]
}

func (x EFriendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EFriendType.Descriptor instead.
func (EFriendType) EnumDescriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

//请求好友列表
type CS_FriendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageIdx int32       `protobuf:"varint,1,opt,name=PageIdx,proto3" json:"PageIdx,omitempty"`
	Select  EFriendType `protobuf:"varint,2,opt,name=Select,proto3,enum=EFriendType" json:"Select,omitempty"` //查询类型
}

func (x *CS_FriendList) Reset() {
	*x = CS_FriendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_FriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_FriendList) ProtoMessage() {}

func (x *CS_FriendList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_FriendList.ProtoReflect.Descriptor instead.
func (*CS_FriendList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *CS_FriendList) GetPageIdx() int32 {
	if x != nil {
		return x.PageIdx
	}
	return 0
}

func (x *CS_FriendList) GetSelect() EFriendType {
	if x != nil {
		return x.Select
	}
	return EFriendType_EFT_None
}

type SC_FriendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     ErrorCode   `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	PageIdx int32       `protobuf:"varint,2,opt,name=PageIdx,proto3" json:"PageIdx,omitempty"`
	Select  EFriendType `protobuf:"varint,3,opt,name=Select,proto3,enum=EFriendType" json:"Select,omitempty"` //查询类型
}

func (x *SC_FriendList) Reset() {
	*x = SC_FriendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_FriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_FriendList) ProtoMessage() {}

func (x *SC_FriendList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_FriendList.ProtoReflect.Descriptor instead.
func (*SC_FriendList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *SC_FriendList) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_FriendList) GetPageIdx() int32 {
	if x != nil {
		return x.PageIdx
	}
	return 0
}

func (x *SC_FriendList) GetSelect() EFriendType {
	if x != nil {
		return x.Select
	}
	return EFriendType_EFT_None
}

//请求添加好友
type CS_FriendAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleSN int64 `protobuf:"varint,1,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
}

func (x *CS_FriendAdd) Reset() {
	*x = CS_FriendAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_FriendAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_FriendAdd) ProtoMessage() {}

func (x *CS_FriendAdd) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_FriendAdd.ProtoReflect.Descriptor instead.
func (*CS_FriendAdd) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *CS_FriendAdd) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

type SC_FriendAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	RoleSN int64     `protobuf:"varint,2,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
}

func (x *SC_FriendAdd) Reset() {
	*x = SC_FriendAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_FriendAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_FriendAdd) ProtoMessage() {}

func (x *SC_FriendAdd) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_FriendAdd.ProtoReflect.Descriptor instead.
func (*SC_FriendAdd) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *SC_FriendAdd) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_FriendAdd) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

//请求删除好友
type CS_FriendDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleSN int64 `protobuf:"varint,1,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
}

func (x *CS_FriendDelete) Reset() {
	*x = CS_FriendDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_FriendDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_FriendDelete) ProtoMessage() {}

func (x *CS_FriendDelete) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_FriendDelete.ProtoReflect.Descriptor instead.
func (*CS_FriendDelete) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{4}
}

func (x *CS_FriendDelete) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

type SC_FriendDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleSN int64     `protobuf:"varint,1,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
	Ret    ErrorCode `protobuf:"varint,2,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_FriendDelete) Reset() {
	*x = SC_FriendDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_FriendDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_FriendDelete) ProtoMessage() {}

func (x *SC_FriendDelete) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_FriendDelete.ProtoReflect.Descriptor instead.
func (*SC_FriendDelete) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{5}
}

func (x *SC_FriendDelete) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

func (x *SC_FriendDelete) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

//请求查询好友
type CS_FriendQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
}

func (x *CS_FriendQuery) Reset() {
	*x = CS_FriendQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_FriendQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_FriendQuery) ProtoMessage() {}

func (x *CS_FriendQuery) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_FriendQuery.ProtoReflect.Descriptor instead.
func (*CS_FriendQuery) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{6}
}

func (x *CS_FriendQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type SC_FriendQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string    `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	Ret      ErrorCode `protobuf:"varint,2,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_FriendQuery) Reset() {
	*x = SC_FriendQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_FriendQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_FriendQuery) ProtoMessage() {}

func (x *SC_FriendQuery) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_FriendQuery.ProtoReflect.Descriptor instead.
func (*SC_FriendQuery) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{7}
}

func (x *SC_FriendQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *SC_FriendQuery) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

//拉黑好友
type CS_FriendBlack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleSN int64 `protobuf:"varint,1,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
}

func (x *CS_FriendBlack) Reset() {
	*x = CS_FriendBlack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_FriendBlack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_FriendBlack) ProtoMessage() {}

func (x *CS_FriendBlack) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_FriendBlack.ProtoReflect.Descriptor instead.
func (*CS_FriendBlack) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{8}
}

func (x *CS_FriendBlack) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

type SC_FriendBlack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleSN int64     `protobuf:"varint,1,opt,name=RoleSN,proto3" json:"RoleSN,omitempty"`
	Ret    ErrorCode `protobuf:"varint,2,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_FriendBlack) Reset() {
	*x = SC_FriendBlack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_FriendBlack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_FriendBlack) ProtoMessage() {}

func (x *SC_FriendBlack) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_FriendBlack.ProtoReflect.Descriptor instead.
func (*SC_FriendBlack) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{9}
}

func (x *SC_FriendBlack) GetRoleSN() int64 {
	if x != nil {
		return x.RoleSN
	}
	return 0
}

func (x *SC_FriendBlack) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

var File_friend_proto protoreflect.FileDescriptor

var file_friend_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x0d, 0x43, 0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x78, 0x12, 0x24, 0x0a, 0x06, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x45, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x22, 0x6d, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x78, 0x12, 0x24, 0x0a, 0x06, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x45, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x22,
	0x26, 0x0a, 0x0c, 0x43, 0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x22, 0x44, 0x0a, 0x0c, 0x53, 0x43, 0x5f, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x22, 0x29, 0x0a,
	0x0f, 0x43, 0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x22, 0x47, 0x0a, 0x0f, 0x53, 0x43, 0x5f, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x53, 0x4e, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65,
	0x74, 0x22, 0x2c, 0x0a, 0x0e, 0x43, 0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x4a, 0x0a, 0x0e, 0x53, 0x43, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x03, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x43,
	0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x22, 0x46, 0x0a, 0x0e, 0x53, 0x43, 0x5f, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53,
	0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x4e, 0x12,
	0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x2a, 0x4c, 0x0a,
	0x0b, 0x45, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x45, 0x46, 0x54, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x46,
	0x54, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x46,
	0x54, 0x5f, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x46, 0x54, 0x5f, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x03, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2e, 0x2f, 0x61, 0x6b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData = file_friend_proto_rawDesc
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_friend_proto_rawDescData)
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_friend_proto_goTypes = []interface{}{
	(EFriendType)(0),        // 0: EFriendType
	(*CS_FriendList)(nil),   // 1: CS_FriendList
	(*SC_FriendList)(nil),   // 2: SC_FriendList
	(*CS_FriendAdd)(nil),    // 3: CS_FriendAdd
	(*SC_FriendAdd)(nil),    // 4: SC_FriendAdd
	(*CS_FriendDelete)(nil), // 5: CS_FriendDelete
	(*SC_FriendDelete)(nil), // 6: SC_FriendDelete
	(*CS_FriendQuery)(nil),  // 7: CS_FriendQuery
	(*SC_FriendQuery)(nil),  // 8: SC_FriendQuery
	(*CS_FriendBlack)(nil),  // 9: CS_FriendBlack
	(*SC_FriendBlack)(nil),  // 10: SC_FriendBlack
	(ErrorCode)(0),          // 11: ErrorCode
}
var file_friend_proto_depIdxs = []int32{
	0,  // 0: CS_FriendList.Select:type_name -> EFriendType
	11, // 1: SC_FriendList.Ret:type_name -> ErrorCode
	0,  // 2: SC_FriendList.Select:type_name -> EFriendType
	11, // 3: SC_FriendAdd.Ret:type_name -> ErrorCode
	11, // 4: SC_FriendDelete.Ret:type_name -> ErrorCode
	11, // 5: SC_FriendQuery.Ret:type_name -> ErrorCode
	11, // 6: SC_FriendBlack.Ret:type_name -> ErrorCode
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	file_errorcode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_FriendList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_FriendList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_FriendAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_FriendAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_FriendDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_FriendDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_FriendQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_FriendQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_FriendBlack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_FriendBlack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		EnumInfos:         file_friend_proto_enumTypes,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_rawDesc = nil
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
