// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: mail.proto

package akmessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMailStatus int32

const (
	EMailStatus_EMS_None EMailStatus = 0 //未读未领取
	EMailStatus_EMS_Read EMailStatus = 1 //已读未领取
	EMailStatus_EMS_Done EMailStatus = 2 //已读已领取
)

// Enum value maps for EMailStatus.
var (
	EMailStatus_name = map[int32]string{
		0: "EMS_None",
		1: "EMS_Read",
		2: "EMS_Done",
	}
	EMailStatus_value = map[string]int32{
		"EMS_None": 0,
		"EMS_Read": 1,
		"EMS_Done": 2,
	}
)

func (x EMailStatus) Enum() *EMailStatus {
	p := new(EMailStatus)
	*p = x
	return p
}

func (x EMailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[0].Descriptor()
}

func (EMailStatus) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[0]
}

func (x EMailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMailStatus.Descriptor instead.
func (EMailStatus) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

type EMailDeleteStatus int32

const (
	EMailDeleteStatus_EMDS_All  EMailDeleteStatus = 0
	EMailDeleteStatus_EMDS_Read EMailDeleteStatus = 1
	EMailDeleteStatus_EMDS_Done EMailDeleteStatus = 2
)

// Enum value maps for EMailDeleteStatus.
var (
	EMailDeleteStatus_name = map[int32]string{
		0: "EMDS_All",
		1: "EMDS_Read",
		2: "EMDS_Done",
	}
	EMailDeleteStatus_value = map[string]int32{
		"EMDS_All":  0,
		"EMDS_Read": 1,
		"EMDS_Done": 2,
	}
)

func (x EMailDeleteStatus) Enum() *EMailDeleteStatus {
	p := new(EMailDeleteStatus)
	*p = x
	return p
}

func (x EMailDeleteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMailDeleteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[1].Descriptor()
}

func (EMailDeleteStatus) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[1]
}

func (x EMailDeleteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMailDeleteStatus.Descriptor instead.
func (EMailDeleteStatus) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

type CS_MailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_MailInfo) Reset() {
	*x = CS_MailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailInfo) ProtoMessage() {}

func (x *CS_MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailInfo.ProtoReflect.Descriptor instead.
func (*CS_MailInfo) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

type MailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailSN        string      `protobuf:"bytes,1,opt,name=MailSN,proto3" json:"MailSN,omitempty"`                   //唯一标识
	ID            int32       `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`                          //配置ID，后台自定义邮件，此值为0
	Title         string      `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`                     //标配，配置可找到，则不需要，否则需要加
	Content       string      `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`                 //内容，如果当前是配置内容，则当前不存，否则，后台运营自定义邮件，则需要填充
	Params        string      `protobuf:"bytes,5,opt,name=Params,proto3" json:"Params,omitempty"`                   //参数[xx,yy,aa...]，有参数则填补，没有则不需要
	Attachments   []*BagItem  `protobuf:"bytes,6,rep,name=Attachments,proto3" json:"Attachments,omitempty"`         //附件,后台运营自定义邮件，则需要填充，特殊情况：配置有，但某功能产出附加，则双方面都需要
	CreateTimeUTC int64       `protobuf:"varint,7,opt,name=CreateTimeUTC,proto3" json:"CreateTimeUTC,omitempty"`    //创建时间
	Creator       string      `protobuf:"bytes,8,opt,name=Creator,proto3" json:"Creator,omitempty"`                 //创建者
	Status        EMailStatus `protobuf:"varint,9,opt,name=Status,proto3,enum=EMailStatus" json:"Status,omitempty"` //邮件状态
	Duration      int32       `protobuf:"varint,10,opt,name=Duration,proto3" json:"Duration,omitempty"`             //持续时间，后台运营设置
	Type          int32       `protobuf:"varint,11,opt,name=Type,proto3" json:"Type,omitempty"`                     //邮件类型，后台运营设置
}

func (x *MailItem) Reset() {
	*x = MailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailItem) ProtoMessage() {}

func (x *MailItem) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailItem.ProtoReflect.Descriptor instead.
func (*MailItem) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailItem) GetMailSN() string {
	if x != nil {
		return x.MailSN
	}
	return ""
}

func (x *MailItem) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MailItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailItem) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *MailItem) GetAttachments() []*BagItem {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *MailItem) GetCreateTimeUTC() int64 {
	if x != nil {
		return x.CreateTimeUTC
	}
	return 0
}

func (x *MailItem) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MailItem) GetStatus() EMailStatus {
	if x != nil {
		return x.Status
	}
	return EMailStatus_EMS_None
}

func (x *MailItem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MailItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SC_MailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   ErrorCode   `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	Items []*MailItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *SC_MailInfo) Reset() {
	*x = SC_MailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailInfo) ProtoMessage() {}

func (x *SC_MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailInfo.ProtoReflect.Descriptor instead.
func (*SC_MailInfo) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SC_MailInfo) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_MailInfo) GetItems() []*MailItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CS_MailRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailSN int64 `protobuf:"varint,1,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *CS_MailRead) Reset() {
	*x = CS_MailRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailRead) ProtoMessage() {}

func (x *CS_MailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailRead.ProtoReflect.Descriptor instead.
func (*CS_MailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *CS_MailRead) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type SC_MailRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	MailSN int64     `protobuf:"varint,2,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *SC_MailRead) Reset() {
	*x = SC_MailRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailRead) ProtoMessage() {}

func (x *SC_MailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailRead.ProtoReflect.Descriptor instead.
func (*SC_MailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *SC_MailRead) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_MailRead) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type CS_MailTake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailSN int64 `protobuf:"varint,1,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *CS_MailTake) Reset() {
	*x = CS_MailTake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailTake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailTake) ProtoMessage() {}

func (x *CS_MailTake) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailTake.ProtoReflect.Descriptor instead.
func (*CS_MailTake) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *CS_MailTake) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type SC_MailTake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	MailSN int64     `protobuf:"varint,2,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *SC_MailTake) Reset() {
	*x = SC_MailTake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailTake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailTake) ProtoMessage() {}

func (x *SC_MailTake) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailTake.ProtoReflect.Descriptor instead.
func (*SC_MailTake) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *SC_MailTake) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_MailTake) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type CS_MailOneKeyRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_MailOneKeyRead) Reset() {
	*x = CS_MailOneKeyRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailOneKeyRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailOneKeyRead) ProtoMessage() {}

func (x *CS_MailOneKeyRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailOneKeyRead.ProtoReflect.Descriptor instead.
func (*CS_MailOneKeyRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

type SC_MailOneKeyRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_MailOneKeyRead) Reset() {
	*x = SC_MailOneKeyRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailOneKeyRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailOneKeyRead) ProtoMessage() {}

func (x *SC_MailOneKeyRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailOneKeyRead.ProtoReflect.Descriptor instead.
func (*SC_MailOneKeyRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{8}
}

func (x *SC_MailOneKeyRead) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

type CS_MailOneKeyTake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_MailOneKeyTake) Reset() {
	*x = CS_MailOneKeyTake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailOneKeyTake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailOneKeyTake) ProtoMessage() {}

func (x *CS_MailOneKeyTake) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailOneKeyTake.ProtoReflect.Descriptor instead.
func (*CS_MailOneKeyTake) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{9}
}

type SC_MailOneKeyTake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
}

func (x *SC_MailOneKeyTake) Reset() {
	*x = SC_MailOneKeyTake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailOneKeyTake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailOneKeyTake) ProtoMessage() {}

func (x *SC_MailOneKeyTake) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailOneKeyTake.ProtoReflect.Descriptor instead.
func (*SC_MailOneKeyTake) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{10}
}

func (x *SC_MailOneKeyTake) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

type CS_MailDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailSN int64 `protobuf:"varint,1,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *CS_MailDelete) Reset() {
	*x = CS_MailDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailDelete) ProtoMessage() {}

func (x *CS_MailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailDelete.ProtoReflect.Descriptor instead.
func (*CS_MailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{11}
}

func (x *CS_MailDelete) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type SC_MailDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	MailSN int64     `protobuf:"varint,2,opt,name=MailSN,proto3" json:"MailSN,omitempty"`
}

func (x *SC_MailDelete) Reset() {
	*x = SC_MailDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailDelete) ProtoMessage() {}

func (x *SC_MailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailDelete.ProtoReflect.Descriptor instead.
func (*SC_MailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{12}
}

func (x *SC_MailDelete) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_MailDelete) GetMailSN() int64 {
	if x != nil {
		return x.MailSN
	}
	return 0
}

type CS_MailOneKeyDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status EMailDeleteStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=EMailDeleteStatus" json:"Status,omitempty"`
}

func (x *CS_MailOneKeyDelete) Reset() {
	*x = CS_MailOneKeyDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_MailOneKeyDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_MailOneKeyDelete) ProtoMessage() {}

func (x *CS_MailOneKeyDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_MailOneKeyDelete.ProtoReflect.Descriptor instead.
func (*CS_MailOneKeyDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{13}
}

func (x *CS_MailOneKeyDelete) GetStatus() EMailDeleteStatus {
	if x != nil {
		return x.Status
	}
	return EMailDeleteStatus_EMDS_All
}

type SC_MailOneKeyDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode         `protobuf:"varint,1,opt,name=Ret,proto3,enum=ErrorCode" json:"Ret,omitempty"`
	Status EMailDeleteStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=EMailDeleteStatus" json:"Status,omitempty"`
}

func (x *SC_MailOneKeyDelete) Reset() {
	*x = SC_MailOneKeyDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_MailOneKeyDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_MailOneKeyDelete) ProtoMessage() {}

func (x *SC_MailOneKeyDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_MailOneKeyDelete.ProtoReflect.Descriptor instead.
func (*SC_MailOneKeyDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{14}
}

func (x *SC_MailOneKeyDelete) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_Invaild
}

func (x *SC_MailOneKeyDelete) GetStatus() EMailDeleteStatus {
	if x != nil {
		return x.Status
	}
	return EMailDeleteStatus_EMDS_All
}

var File_mail_proto protoreflect.FileDescriptor

var file_mail_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x69,
	0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x53, 0x5f,
	0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xbc, 0x02, 0x0a, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2a, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x67,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x55,
	0x54, 0x43, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x55, 0x54, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4c, 0x0a, 0x0b, 0x53, 0x43, 0x5f, 0x4d, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x03, 0x52, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x22, 0x43, 0x0a, 0x0b,
	0x53, 0x43, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69,
	0x6c, 0x53, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53,
	0x4e, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x61, 0x6b, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x22, 0x43, 0x0a, 0x0b, 0x53, 0x43, 0x5f, 0x4d,
	0x61, 0x69, 0x6c, 0x54, 0x61, 0x6b, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x22, 0x13, 0x0a,
	0x11, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x61, 0x64, 0x22, 0x31, 0x0a, 0x11, 0x53, 0x43, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c,
	0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x6b, 0x65, 0x22, 0x31, 0x0a, 0x11, 0x53, 0x43,
	0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x54, 0x61, 0x6b, 0x65, 0x12,
	0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x27, 0x0a,
	0x0d, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x22, 0x45, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x4d, 0x61, 0x69,
	0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x4e, 0x22, 0x41, 0x0a,
	0x13, 0x43, 0x53, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x5f, 0x0a, 0x13, 0x53, 0x43, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x65, 0x4b, 0x65,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2a, 0x37, 0x0a, 0x0b, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4d, 0x53, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x45, 0x4d, 0x53, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x45, 0x4d, 0x53, 0x5f, 0x44, 0x6f, 0x6e, 0x65, 0x10, 0x02, 0x2a, 0x3f, 0x0a, 0x11, 0x45, 0x4d,
	0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0c, 0x0a, 0x08, 0x45, 0x4d, 0x44, 0x53, 0x5f, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x45, 0x4d, 0x44, 0x53, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x4d, 0x44, 0x53, 0x5f, 0x44, 0x6f, 0x6e, 0x65, 0x10, 0x02, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2e, 0x2f, 0x61, 0x6b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData = file_mail_proto_rawDesc
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_mail_proto_rawDescData)
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mail_proto_goTypes = []interface{}{
	(EMailStatus)(0),            // 0: EMailStatus
	(EMailDeleteStatus)(0),      // 1: EMailDeleteStatus
	(*CS_MailInfo)(nil),         // 2: CS_MailInfo
	(*MailItem)(nil),            // 3: MailItem
	(*SC_MailInfo)(nil),         // 4: SC_MailInfo
	(*CS_MailRead)(nil),         // 5: CS_MailRead
	(*SC_MailRead)(nil),         // 6: SC_MailRead
	(*CS_MailTake)(nil),         // 7: CS_MailTake
	(*SC_MailTake)(nil),         // 8: SC_MailTake
	(*CS_MailOneKeyRead)(nil),   // 9: CS_MailOneKeyRead
	(*SC_MailOneKeyRead)(nil),   // 10: SC_MailOneKeyRead
	(*CS_MailOneKeyTake)(nil),   // 11: CS_MailOneKeyTake
	(*SC_MailOneKeyTake)(nil),   // 12: SC_MailOneKeyTake
	(*CS_MailDelete)(nil),       // 13: CS_MailDelete
	(*SC_MailDelete)(nil),       // 14: SC_MailDelete
	(*CS_MailOneKeyDelete)(nil), // 15: CS_MailOneKeyDelete
	(*SC_MailOneKeyDelete)(nil), // 16: SC_MailOneKeyDelete
	(*BagItem)(nil),             // 17: BagItem
	(ErrorCode)(0),              // 18: ErrorCode
}
var file_mail_proto_depIdxs = []int32{
	17, // 0: MailItem.Attachments:type_name -> BagItem
	0,  // 1: MailItem.Status:type_name -> EMailStatus
	18, // 2: SC_MailInfo.Ret:type_name -> ErrorCode
	3,  // 3: SC_MailInfo.Items:type_name -> MailItem
	18, // 4: SC_MailRead.Ret:type_name -> ErrorCode
	18, // 5: SC_MailTake.Ret:type_name -> ErrorCode
	18, // 6: SC_MailOneKeyRead.Ret:type_name -> ErrorCode
	18, // 7: SC_MailOneKeyTake.Ret:type_name -> ErrorCode
	18, // 8: SC_MailDelete.Ret:type_name -> ErrorCode
	1,  // 9: CS_MailOneKeyDelete.Status:type_name -> EMailDeleteStatus
	18, // 10: SC_MailOneKeyDelete.Ret:type_name -> ErrorCode
	1,  // 11: SC_MailOneKeyDelete.Status:type_name -> EMailDeleteStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	file_errorcode_proto_init()
	file_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailTake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailTake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailOneKeyRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailOneKeyRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailOneKeyTake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailOneKeyTake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_MailOneKeyDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_MailOneKeyDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		EnumInfos:         file_mail_proto_enumTypes,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_rawDesc = nil
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
