// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: serverRpc.proto

package akmessage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//L2G_GET_ROLE_NUM_REQ
type L2G_Get_Role_Num_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *L2G_Get_Role_Num_Req) Reset() {
	*x = L2G_Get_Role_Num_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2G_Get_Role_Num_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2G_Get_Role_Num_Req) ProtoMessage() {}

func (x *L2G_Get_Role_Num_Req) ProtoReflect() protoreflect.Message {
	mi := &file_serverRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2G_Get_Role_Num_Req.ProtoReflect.Descriptor instead.
func (*L2G_Get_Role_Num_Req) Descriptor() ([]byte, []int) {
	return file_serverRpc_proto_rawDescGZIP(), []int{0}
}

//G2L_GET_ROLE_NUM_RSP
type G2L_Get_Role_Num_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles int64 `protobuf:"varint,1,opt,name=Roles,proto3" json:"Roles,omitempty"`
}

func (x *G2L_Get_Role_Num_Rsp) Reset() {
	*x = G2L_Get_Role_Num_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2L_Get_Role_Num_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2L_Get_Role_Num_Rsp) ProtoMessage() {}

func (x *G2L_Get_Role_Num_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_serverRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2L_Get_Role_Num_Rsp.ProtoReflect.Descriptor instead.
func (*G2L_Get_Role_Num_Rsp) Descriptor() ([]byte, []int) {
	return file_serverRpc_proto_rawDescGZIP(), []int{1}
}

func (x *G2L_Get_Role_Num_Rsp) GetRoles() int64 {
	if x != nil {
		return x.Roles
	}
	return 0
}

var File_serverRpc_proto protoreflect.FileDescriptor

var file_serverRpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x32, 0x47, 0x5f, 0x47, 0x65, 0x74, 0x5f, 0x52, 0x6f, 0x6c,
	0x65, 0x5f, 0x4e, 0x75, 0x6d, 0x5f, 0x52, 0x65, 0x71, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x32, 0x4c,
	0x5f, 0x47, 0x65, 0x74, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x4e, 0x75, 0x6d, 0x5f, 0x52, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x61, 0x6b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serverRpc_proto_rawDescOnce sync.Once
	file_serverRpc_proto_rawDescData = file_serverRpc_proto_rawDesc
)

func file_serverRpc_proto_rawDescGZIP() []byte {
	file_serverRpc_proto_rawDescOnce.Do(func() {
		file_serverRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_serverRpc_proto_rawDescData)
	})
	return file_serverRpc_proto_rawDescData
}

var file_serverRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serverRpc_proto_goTypes = []interface{}{
	(*L2G_Get_Role_Num_Req)(nil), // 0: L2G_Get_Role_Num_Req
	(*G2L_Get_Role_Num_Rsp)(nil), // 1: G2L_Get_Role_Num_Rsp
}
var file_serverRpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serverRpc_proto_init() }
func file_serverRpc_proto_init() {
	if File_serverRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serverRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2G_Get_Role_Num_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2L_Get_Role_Num_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serverRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serverRpc_proto_goTypes,
		DependencyIndexes: file_serverRpc_proto_depIdxs,
		MessageInfos:      file_serverRpc_proto_msgTypes,
	}.Build()
	File_serverRpc_proto = out.File
	file_serverRpc_proto_rawDesc = nil
	file_serverRpc_proto_goTypes = nil
	file_serverRpc_proto_depIdxs = nil
}
